Migrate Pages
Galaxypedia-Wiki/Galaxypedia pull request #67
Opened 2024-12-18 03:12 UTC by sharpy66

Known issues:
Category page redirects do not work,
Tables are not formatted properly,
Collapsible elements like those on the main ships page do not work,
Category pages are bare-bones,
There are only ship infoboxes(others are skipped as no replacement currently exists in hugopedia),
User and special page links do not work,
Main/home page has no links (use the search bar to get anywhere),

Definitely more things I am not aware of at this time.

2024-12-18 03:16 UTC, cswimr commented
@sharpy66 Can you please format this PR with prettier so checks pass and the preview deployment can be made? Not sure why preview deployments aren't being made on PRs that fail formatting checks, will look into that later.

2024-12-18 14:03 UTC, smallketchup82 commented
> Known issues:
> - Category page redirects do not work

category page redirects not working is fine
> - Tables are not formatted properly

weird. pandoc should've formatted them correctly, but i digress. might be wise to keep track of pages like these. maybe via a hugo tag
> - Collapsible elements like those on the main ships page do not work

perfect. hate those
> - Category pages are bare-bones

this ties into #20 
> - There are only ship infoboxes(others are skipped as no replacement currently exists in hugopedia)

i did go through other templates and honestly didnt see much of a need for them. if you could give me a list of templates you  need, i can go through them and see which ones i want to keep
> - User and special page links do not work

the idea was that user links would be converted to github user links. but most of the community wouldnt have a github account, which begs the question as to why @cswimr spent 9 years working on the github user link template 😭

but regardless, we can probably switch them to their roblox profiles, or just remove them. special page links should just be deleted
> - Main/home page has no links (use the search bar to get anywhere)

should probably make an issue for this

2024-12-18 14:13 UTC, smallketchup82 requested changes
why are the ships under `content/wiki`? they should be under `content/wiki/ships`

2024-12-18 14:17 UTC, smallketchup82 commented
PR in general is good. i definitely can see some issues and i think that links are done rather weirdly (whats with all of that ref stuff?) but nothing we cant work through. good work!

2024-12-18 15:49 UTC, sharpy66 commented
> why are the ships under `content/wiki`? they should be under `content/wiki/ships`

I don't know how or why, but that commit specifically was simply the /ships/ folder... and nothing else.

2024-12-18 15:51 UTC, sharpy66 commented on content/wiki/Fighters/Bonehawk.md
> +{{< shipInfobox >}} {{< notices/limitedShip >}} The **_Bonehawk_** is an exclusive [Fighter]({{< ref "/categories/" >}}fighters) only found on the [Kapisi]({{< ref "/wiki/" >}}Kapisi).
That isn't due to prettier, the script is based on an older version of Deity.md which had them placed like that. Simple change.

2024-12-18 16:13 UTC, smallketchup82 commented
looking a lot better now! will review it when i get the time

2024-12-18 17:55 UTC, cswimr commented on content/wiki/Fighters/Bonehawk.md
> +{{< shipInfobox >}} {{< notices/limitedShip >}} The **_Bonehawk_** is an exclusive [Fighter]({{< ref "/categories/" >}}fighters) only found on the [Kapisi]({{< ref "/wiki/" >}}Kapisi).
It actually is due to Prettier, but there's a simple fix for it. See how the shortcodes are formatted in the Ships archetype. That's more compliant with markdown anyway, as newlines in markdown are not newlines unless the line above the newline contains two trailing spaces.

Invalid:
```markdown
{{< shipInfobox >}}
{{< notice/limitedShip >}}
The ...
```

Valid:
```markdown
{{< shipInfobox >}}

{{< notice/limitedShip >}}

The ...
```

2024-12-28 04:59 UTC, smallketchup82 commented
@Galaxypedia-Wiki/development-team this PR looks good to me and i'd like to get it in if possible. what's the plan here? do we want to get categorization in before we merge or is it fine to merge as is?

2024-12-28 05:02 UTC, cswimr commented
I believe this has category pages, right? They're just barebones?

2024-12-28 05:03 UTC, cswimr commented
Yeah it does, see: https://sharpy66-migrate-pages.galaxypedia.pages.dev/categories/carriers/

2024-12-28 05:03 UTC, smallketchup82 commented
right, it does. so are we all good here?

2024-12-28 05:05 UTC, cswimr commented
Looks like taxonomy pages are a bit broken, gonna update this branch and see if it's fixed on rebuild.

2024-12-28 05:10 UTC, cswimr commented
Not sure if that'll fix taxonomy pages completely but it's a start

2024-12-28 05:13 UTC, cswimr commented
Footer fix is OOS for this pr, we should either fix it before merging this and update this branch after, or do it later. Will require refactoring of the footer partial.

2024-12-30 20:04 UTC, smallketchup82 commented
@cswimr like i've said before i really don't want to wait on this PR any longer. if the remaining issues can be weeded out after the fact, that'd be good.

let's have our priorities on merging this asap. i'll set a deadline of before the end of this year if it helps

2024-12-31 22:54 UTC, cswimr approved these changes

2025-01-01 00:03 UTC, smallketchup82 commented
i'm on mobile and can't load the diff screen cause it's too big. so i can't approve.

just consider this approved

2025-01-01 00:03 UTC, merged